from dotenv import load_dotenv
from reason_finder import get_full_info, reason_extractor
from db_init import query_by_id, SQLiteUtility
import os
from util import chatgpt_wrapper, chatgpt_wrapper_16k, chatgpt_wrapper_4
import json
import uuid
from datetime import datetime


def chat_sum(text):
    sys_temp = "You are a helpful assistant who summarize the transcription of a meeting's audio recording into 10% " \
               "of " \
               "it's " \
               "original length. The transcription is automatically produced so it may contain many mistakes."
    result = chatgpt_wrapper_4(sys_temp, text)
    return result


text = """
Ja, genau, wie eine Sendung über leitwolfs denn so passiert süsse deine Termine, also zwischen Onboarding und Inzell Konzeption und in dieser Konzentration und Folge Konsultation und da haben wir uns schon Gedanken gemacht, was passiert mit dem Chat bot oder was ich sprechen sie tut auch was läuft. Alf aus dem Chat bot bereits Momentanverbrauch wird initial Kunst und was passiert denn aufgrund Sophie Baukunst Verluste solenis notizie detaillierter of Chatbots über Leid und ihren Leuten sitzt aufgrund full Interview wissenschaftliche sieht ja, also ich könnte jetzt direkt einsteigen Socken mit grundsätzlichen Fragen zum au.
 Aufbau weil ich glaube das ist ja eigentlich kommt ja mega drauf an, was wollen wir eigentlich genau rausfinden mit der Evaluation, also z.b. Brauchtest das Onboarding überhaupt, weil das Onboarding hatten wir jetzt um daten zu sammeln, wie wie der Patient lebt, damit wir eine möglichst gut auf ihn zugeschnittene Therapie machen können, jetzt ist der Fokus oder das Go könnte er komplett anders sein, wir können mal einfach sagen, der Patient kommt zum Arzt machen Therapieplan und möglichst gut wird es während der vier Wochen, also was soll denn in dem Onboarding passieren bleibt es trotzdem eine Therapie für also bleibt es in Therapie Tagebuch schreiben, weil wenn man halt ja schon in der ersten kommt, eine super gut individualisierte Therapie gemacht hat.
 Was soll denn da noch groß der Jackpot tun, dass du das für dich schon mal hinterfragen was soll ich genau wollen wir im Onboarding Boom reparieren lufteinlassfilter besprechen und überlege ist für die Vorlauf 35% recht vertraut Wochenmitte technische Gerätschaften Spülbecken Unterbau contenti, das mögen deine bringe ich Urlaub und und die führen oder und das andere ist nicht funktioniert verlieren rai.it, deine Therapie Voss in Außenwand beim Rangieren und technische Probleme nach vorne Zwischenkonto, dass ich so erledigt und die zwei überlege ich das aber das stimmt das.
 Jenachdem nehme was es sich zu nehmen evaluieren aber Frau Geschäften trotzdem geschieht, wenn was macht, das natürlich muss das Onboarding die Patienten vorbereitet oder die Initialen oder und damit ich dann eine ganze außer der ganze zweite Teil vom ersetzt Wamser wie Verbrecher mit deiner Resultat ist, im ersten Teil 7 und 1. Liga Modus oder was hat eine beliebige Edition sofort zu deiner Wohnung Regisseur Schokoladenpudding mit der Definition über eine Woche für Tagebuch zu deinem Lebensstil oder was? Also müssen wir alle Chat-Kommunikation?
 Easybox wird zur Legende, was macht gern Triebachse internationalen das und dann eben warst du heute schon deinen Tracker synchronisiert und sowas wäre jetzt dann irgendwas mit der Technik kochen oder sollen wir die Initialen korrigieren und das wird dann mit der Therapie anfangen, aber da müssen wir dann auch wirklich definieren, was sind ihre Aufgaben in der Woche außer schaut täglich einmal rein und sprich mit diesem Board ebenso, als weil solange die noch keine Maßnahme haben, wofür ist diesen Jacob raucht ist es so bisschen ja, willst du einfach in die Fitbit App gucken?
 Da mal schauen, was da läuft, oder was? Also, was sollst du denn falsch machen kann die Uhr einfach tragen, aber ob es funktioniert ist natürlich eine gewisse baseline. Das liefert dir unter Umständen sozusagen Formationen dazu, wie die Person zu sagen. Zumindest grob normal lebt, also ich kenne aber dann müssen wir eben schon genau das wissen, was wir daraus ziehen, wollen wir einfach die Aktivitäten oder wollen wir einfach sämtliche Patientendaten von Herzrate bis irgendwas da schon ziehen, das muss mir irgendwie definieren, was wollen wir was wollen wir also was machen? Die machen einfach zum Drucken, es funktioniert ganz simpel und Gryffindor Terminvorschlag, was auf die Fitbit App sehr einfachen drin großen Offizier und dann haben wir bis unten sehen, was passiert.
 Ruhepuls oder was also oder Imbiss Patientensicherheit oder machen Apps funktioniert nach Intervention funktionieren funktioniert, also die Wände vorbereitet zum zum verschiedene Therapien nicht nur das sondern sie haben ja gelernt, wie gestalten Sie eine gute initial Konsultation und wenn man das jetzt sozusagen nicht so gut macht einfach, weil man etwas vorne spart, dann liefert nur an den neu richten eine sage ich mal schlechter Initialen Konsultation und welche sozusagen Einflüsse das auch eventuell weitere Therapie hat, das wissen wir nicht. Also das ist dass es so der sagen, dass das was
 Bei mir mitspielt alles machen, dass man doch noch die Leute so sagen, wenn hier das schon gelernt haben, dann sollten wir das doch anwenden. Wenn er halt auch also wenn wir jetzt eben schon so Sachen machen und dann sozusagen schon Daten Zähne aus Aussehen Signal, dann würde ich mir auch überlegen, ob man den nicht halt die auf also das ist eben je nachdem, was wir da definieren wollen, aber also die Aktivitäten sind ja entweder Aktivitäten, die die Uhr irgendwann von selbst erkennt, wenn man bei weil es eben erkannt wird. Er macht eine Weile eine bestimmte Bewegungsform oder du kannst ja manuell anschalten und sagen, jetzt gehe ich loslaufen und vielleicht ist das auch eine Aufgabe, dass man das alt einmal ausprobiert und es anmacht, außer wenn wir sagen, weil das ist nämlich also kann mir schon vorstellen, dass das für alte Leute noch irgendwie Jackie wird, dass man da
 Jetzt hier in Aktivitäten im Training reingeht und dann keine Ahnung wandern oder laufen auswählt und dann einmal Start drückt und dann wieder stoppt, wenn es vorbei ist, weil das ist alles das kann man auch alles aus dem Garten ziehen. Ist das was was selbst gestartet wurde oder ist das eben automatisch erkannt und wollen wir eben den Leuten die Möglichkeit geben, dass sie auch das weil dann wird's am taller genauesten, dann geht das selber stellen und Stunden verbringen wollen, dann dann müssen wir dafür, das würde ich dann Imbiss Onboarding zeiten drei nehmen kosten Anleitung für und so perfektionieren und und je nachdem aber magst das nicht funktioniert mit dem Chat Video, ich will jetzt nicht wieder was rein, aber ich meine
 Wenn das Ding erkennt, die Person hat, die und die Aktivität gemacht oder ist es eingetragen und das ist ja eine ideale Vorlage für Chatbot, um proaktiv drauf zu reagieren. Hey, ich habe heute gemerkt, du bist gelaufen, wie ging es dir dabei, aber aber ich habe gemerkt. Hey, du hast was bisschen was trainiert oder was hast du denn genau gemacht? Wenn das alles nicht erkennt, also, man kann es schon sozusagen fast wieder aktiv und hat dort Steuern, wenn es nicht erkannt worden ist ist man kann das natürlich so machen, dass man das über Fitbit versucht zu machen oder man integriert das einfach in die app das nicht erkannt worden ist. Kann ich jetzt nicht ganz nachvollziehen, also mein Training oder die Fitbit erkennt eben nachher bei dir selbst, also willst du jetzt willst du jetzt einfach wenn man was selber erkennt, als wenn die Poland also nicht selber sondern die Fitbit?
 Etwas das man in dem Fall dann einfach mit dem mit dem Patienten drüber plaudern oder Ja und sagt zuerst ja schön, du hast dich bewegt. Okay, aber nicht mal das können wir ja so oder so, ob man anfängt oder nicht, aber ich weiß es nicht ich ganz ehrlich, also je nachdem was uns erkennen kann. Ich meinte, es könnten Informationen liefern, ich weiß es nicht, ob es sind nimmt kein sozusagen, der eine hat gejoggt und der andere hat irgendwie ist es schwimmen gegangen, ich weiß nicht, ob solche Granularität erkannt wird von Fitbit, weil dann kann man das natürlich Information mitliefern und wenn wenn es mir ja eben dann kann dann kann der Chatbot direkt anfangen mit Hey, ich habe gemerkt, du hast heute und du bist heute geschwommen und wie war es so, dass er nach den red Informationen über die Stadt
 Mein in die Zeit zwischen den Konten kommt, dass man einfach so ja cool du hast dein Training gemacht und dann einfach darüber reden, wie ging es dir damit blabla, aber das war halt einfach irgend irgendwelche Anleitungen Maßnahmen hat oder wie kleine aus gebelein damit man erstmal sich vertraut macht mit der Uhr besonders wichtig, dass ok wichtige Person hatte merken der Chatbot Literatur, dass die Leute eine bestimmte, also wir haben das Onboarding Vater genannt, aber das läuft eine bestimmte Zeit brauchen, um um Vertrauen aufzubauen und Schottland und das kann dann entsprechend, wenn Sie das anfangen zu nutzen und sind erst mal so bisschen.
 Ein bisschen 5 bisschen kniffliger, der wollen nicht und soweit dann kann die ersten thial Konsultation dazu genutzt werden das zur Info essen, was man kann dann die die Ärztin der Arzt kann, dann erklären und sagen hey, dass das wirklich hilfreich und so und wenn man das Chatbot erst auf sie los lässt nach Inzell Konsultation und hast du eben diese Experimentierphase erst danach und wenn sie dann irgendwann eine Woche entscheiden hält, das bringt mir nichts, weil sie einfach nicht gesehen haben, was nun bringt, dann dann haben wir keine Möglichkeit mehr zu zudem reinforcement positiven Fall, dass man durch Arzt uzunov darauf zuzugreifen das nicht noch mal so eine Überlegung dieser dieser Trust Aufbauphase auch zu auf zu machen Druck zu deinem ist Mirela gesagt hat na oder andere portrait trackriders Neuseeland Geschichte.
 Wie schaut dorthin bietet die Kameras kriecht an oder und das muss ich mir überlegen, dass sie morgen übrigens Hashimoto Patienten Hauptstadt Graubünden ich will nur sagen, was das für eine psychologische Komponente hat. Also, das ist so essstörungs technisch, also es kann auch schieflaufen, wenn die Leute sich aufregt und das Singen genaue Kenntnis wo man versteht nichts und die andere Stress Nöten.
 Barbara auch mit einer Barbara absprechen, weil ich glaube nämlich ein normaler Hausarzt sagte, ewig dich nie täglich, weil du hast doch als Frau irgendwie bis zu zwei Kilo Schwankungen über deinen Zyklus und wenn du das dann immer für bare Münze nimmst, also ich ja nur so sagen, dass das halt auch Leute total unter Druck setzen kann und das würden wir nie erklären Sie mich gern Regionalverband Braun davon free stoffwunder vorhandenen oder mercedes.me leitersicherung Sonnenuntergang Dämmerung Haus. Hüttental ich mir draußen im alten Konzept hat die Boeing sitzt im neuen Namen.
 Deine Streams auf einmal verlautbaren. Sei nicht traurig im innenauge das abenteuerlichste neuligen ständig durch die Chatbot über Netzwerk Untermain. Quasi der Favoriten das Bezirks ist hintere versteckt er sich vertraut machen mit meiner Therapieoptionen bewusster und besser informiert. Die kannst das und dass ich ihm Ihnen auch wichtig sei gewarnt dass ich habe die Resultate sprechen unsere bisher und dann frage ich mache das mit der Sache mit dem Scheiß machen, wie das alles irgendwie programmierten.
 Option dazu sagen. Okay, wir versuchen auf Ihre Frage umfassend informieren über die über die Therapieoptionen Wiederherstellung, ich finde es auch sinnvoll, weil es gibt ja unterschiedliche Lernmechanismen bei Leuten und einige reagieren positiv aufs Chat Ball auf das Chatbot oder Motivation Perspektiven eingetragen. Positiver Stadtbad und andere werden positiv reagieren, vielleicht auch etwas auslösen könnten in Ruhe, ohne dass sie unterbrochen werden durch irgendwelche Nachrichten und so weiter. Also, ich finde es ich finde sinnvoll, dass man sozusagen parallel Angebotes zu sagen hat Fragebogen von Maßnahme Farbton.
 Impulstechnik c3003 kennenlernen auf da gibt's Informationen und so weiter, wenn du das willst, oder war das so auf der interveniert an die Presse Messe oder wann es passiert ist und dass Verbraucher durch Interventionen Autohaus in der Fabrik reparieren und dann seht doch das will doch mal Planungshandbuch gut und mach mal genau so eine Woche oder wie?
 Cool und dann hatte ich mir also genau ich hatte ebenso Ablauf zum Ablauf hätte ich dann noch die zweite Frage gehabt, was wird genau in der zweiten Konz besprochen gibt es dann noch Anpassung oder macht es gar keinen Sinn da der Patient ja schon Anpassung während der Zeit allein vom Chatbot erhalten hat, die Folge grundschneide überlegt, was es braucht. Alles passiert nicht nur, weil der 1. Ist die erste eigentlich deckungsgleich mit der
 Bisherigen das macht also, weil das würde für mich Sinn machen, es ist einfach aufgrund, also auf Basis der der gesammelten Erkenntnisse die oder der Eingaben des Patienten wird wieder in individueller Therapieplan erstellt genauso mit dem wo wollen wir hin, was ist realistisch haben überhaupt noch Ernährungs müssen wir etwas machen. Dann der Hunger ja ja genau, aber haben wir dann überhaupt also genau was kann der Chat Portal dazu beitragen, dann später grenzmaße gemeinsam sitzen und darunter citation Report Italjet.
 Enrostar ist deine Chance Information über Depressionen, ich wollte so spricht doch nicht diskutieren wir heute morgen das Haus tatsächlich die Möhrchen und angebotenen Therapieoptionen Island im Vergleich zu bisher bisher sind unübersichtlich sind und man das Haus nicht warm relativ drastische offenbar weniger das Bier gewinnt überlegen. Präsentierte Werther Westf Werther Zentrum der Bewegung wird er ganz feucht.
 Deutscher Begriff Yamaha, da hatte ich ja mal was raus geschrieben und Manuel ist gemacht und was überhaupt in der letzten Konz angewendet wurde er in der letzten Evaluierung oder bist du immer also weißt was ich meine, was ich mal rum geschickt habe dir also dieses ich würde das auf jeden Fall reduzieren, aber was ist denn wenn jetzt dann an einer anfängt und sagt, aber ich mache immer genau mein Pilates und dann melde das mit aufschreiben sollen das einfach aufschreiben, als was was daneh getrackt wird oder Schönau individuelles Name konzentrieren, sondern was gemacht wird oder schwimmen.
 Gagfah von bruce spazieren gehen oder das mit der Option Option passieren TV-Schränke viel passieren die Toten oder was auch immer, das kommt immer auf Basis von Zeit machen. Dann machen wir's implementation technisch schwieriger auch das was man halt aus der Jack, also aus der Fitbit Epi ziehen kann, du musst einfach nur seiner mehr gespürt geschrieben werden, der also mehr braucht mehr Logik hinten drin immer sagen ist Schwimmen Zeit gehen Zeit was auch immer wandern Zeitphase, dass wir in Technik nöthnitz ihn auf die crytivo Auto technische limitieren und ruf an den Zehen auf die Kleidung in Ireland oder das dass wir ich davor warnen oder will.
 Autohaus Timmers nicht auf echte vorrätig das mal Versand, es gibt ein Tages schrittziel oder und dass ich nötig lief Intervention wird, das muss ein Patient Gott der Hauptgrund nur extrem vorsichtig war willst nicht, dass das so schwierig ich wieder nicht halt einfach nicht mit dir gemacht der Couch ich versuche ich ja mehr Strom an zu kriegen, aber irgendwie scheint mir alle also scheint das Kabel kaputt zu sein und ich habe gedacht ich die Steckdose egal sorry
 Unruhig bin hoffe, dass sie ja genau also dass genau das macht einfach Mehraufwand in z.b. Wenn man sagt Tagesziel aber das erst am nächsten Tag abfragen, weil man darf ja noch bis 24 Uhr laufen oder wird immer dann also da einfach meine Mutter war über paar mehr Sachen nachdenken. Tagesrätsel ist einfach nicht vergessen vormittags 30 minuten Maßnahmen die Verteidigungsmaßnahmen ohne ohne Zeitangabe, das ist nicht so schwierig sein Vertriebsnetz.
 Original Befund vom vierten Teil oder das ist nervig, aber dass ich so oder so nicht immer zu hoch sind außerdem aus, also genau das wichtigste fischer-riepe, also, wenn du unbedingt abwegig Software verschrieben elevator sehr authentisch tarrington House down 2.
 Genau. Ja genau, das wollte ich noch mal fragen, was wir der in uns bisher geschrieben haben ist so fünf Aktivitäten werden erkannt, das steht in dem Antrag und sind Aktivitäten aber auch Ernährungsmaßnahmen oder sind das nur Bewegungs Maßnahmen, aber ja eben erkennen im Sinne von erkennen dadurch, dass der Chatbot es herausfindet oder wie wurde operiert, ohne dass mit trotzdem davor drücken okay oder dieselbe einfach fünfsatz Beispiel unterschiedliche Aktivitäten spazieren Schrittzahl schwimmen und dann noch.
 Keine Ahnung Gemüse gegessen und gut, wie mir schon Anrufe da drauf drücken, dass damit die Bedeutung cionet fotomaster muss in einer Petition, das heißt man weniger Maßnahme zur Auswahl weiterführende Informationen Nachrichten Schiwa nächsten Maßnahme zur Person auf, das ist Adidas ein Riese Riese und dann haben wir die Fragebogen von etavis. Marbossa der schnellste Gold auf Opiate, außerdem ist mir sicherer überarbeitetes normal.
 Betreutes Wohnen mit Herz Dame für ein Team auch alles mit einer Karotte und Lukas ist ein Fragebogen, das ist so ein sowieso eine generelle Anamnese macht so, was ist besser und hast du Krankheiten? Ja, der Wein war ein bisschen schlecht geschrieben bzw. Das was man dann einfüllen konnte, hat manchmal nicht sauer zwar nie ganz klar, die Fragen waren manchmal böse und diamanten ist das aber nachher gut dann Initiators was mitnehmen.
 Onboarding und plane oder was ist jetzt hat er Focus Film Erfolgsversprechen die Maßnahmen aufmacht, mit dem wo in Menschenmenge modus das eigentlich sobald? Ich hoffe, dass der Sport für Kunst ist das dein voller Sonne Strand und im Moment auch so zeit.de Nation Stewardess blau nichts tun wir ja noch die anderen noch das Journal bekommen. Wenn das jetzt der Chatbot macht, dann weiß ich nicht. Also, die müssen halt eine Form finden, wie das wieder aufbereitet wird. Visuell, dass man
 Halt die Informationen hat die jetzt eben nie aus dem Journal kommen, sondern aus dem Chat bot alles gleichzeitig auf den Kontakt komplett anders, das muss neu überlegen auf dem Ausnahmefall meinte, dass Franzi Reindl blieben Trainingsbedarf Blusenkleid schwarz das mit der Augsburger ausdruckst. Anderson Option wäre natürlich Antworten Fragebogen Auswertung, wann müssen, dann werd erstmal gucken und Wasser.
 Wer ist eigentlich nur ein austurland 20 Uhr Vorbereitung nimmst mich fotografieren. Ja, das war eben, dass ich das war schon, dass das hat alles ein bisschen zerstört zu den also den den Sinn von alles ist an einem Ort und ob das wäre eine Petition, 55 und dabei unterstützt genau dasselbe meiner Meinung nach, also ziel und Zweck und Besitzer unterschiedlich.
 Sprech und 2. Der Natur aus unterstützt sie gut überlegt sein, ich finde es so so zurück zu der Frage sozusagen, wann muss man da vorbereiten im Sinne sagen diese ganze Chatbot Geschichte Juno zusammenfassung, das war ja vorher sono zusammenfasst und jetzt wäre das sozusagen aus dem Chat Wort. Da gibt's durchaus Möglichkeiten, die von GPT angeboten werden Chats zusammenzufassen, also pro Tag oder eben auch das ja irgendwie überlegen, wie also, dass es cool war, dass man halt so Sachen auch visuell aufbereitet hatte und eben.
 So ging's mir und Bilder und und und und und und genau und ja diese Sachen ob man soll man dann im Chat auffordern zu fotografieren, was hast du heute gegessen? Geht das ja solches Zeug sollen wir da genau dasselbe, weil das war ja schon das coole man hat so auf einem schnellen Blick gesehen. Hier den Patienten ging es an dem Tag scheiße, was ist da passiert so und was mir reden vor der Zeit hat das Zusammenführen a noch nicht besprochen total, dass man eben auch dir die wohnt. Die Funktion ideale wissen, wir trinken während. Also das melden sich noch überlegt wir oder der Chat musst du das auch fordern ja natürlich.
 Wann du jetzt auch im Internet ich muss jetzt Notizen Hochwasser Dezember so die Funktion aus Wertetabelle Funktion hat die Dokumentation einer Hand Zusatz bisherige schon einfach nur noch irgendwie jedesmal ab, wenn genau wenn du ein Foto machst mir was abgezogen. Die Fabrik wurde zudem von dir so also z.b.
 Militär in der Berufswelt die Funktion Seite legen, wenn er merkt, er hat sozusagen der Patient hat kein kein kein Foto gemacht, könnte der Chatbot sozusagen das anregen, willst du jetzt ein Foto machen und sowieso Verbindung zu PC braucht die Fotofunktion Vodianova ja, dann haben wir haben gestern jetzt schreiben wir mal vor der initialen Therapie.
 Nein, wir können jetzt da ich wirklich so durchgehend im Kalender festhalten Visa Card und dann potatoes wieder Gartenkalender ist ja peinlich, also Mann hatte eben diese journaleinträge die können wegfallen, außer man will einfach eine separate Funke Fotofunktion haben. Finde ich jetzt aber vielleicht bitte unnötige, ich würde einfach sagen, man hat nur noch die Maßnahmen im kalender und dann kann man auf eine Maßnahme draufgehen.
 Dann hatten wir eben fertig mit Mirella da diskutiert. Ja, was machen wir denn noch? Wollen wir trotzdem sowas haben wir ja ich kann angeben, wie es mir dabei ging oder ob ich es gemacht habe, ja oder nein? Und der Patient kann halt dann da der Jackpot kann das irgendwie abgleichen und das hinterfragen oder gibt's da eigentlich gar nichts mehr, außer dass die Maßnahmen einfach angezeigt wird, dass du dich daran erinnerst Eier das wollte ich machen, das wär doch irgendwie dein Auto quasi uns Triggerpunkt Gesäß IDZ Pod zum reagiere aus Wismar Sonnenkorona der nächsten Osnabrück wird oder nicht Durchführung von Jackpot.
 Wie reagiert genau? Ja stimmt Sozialsenatorin Tussaud Symbol trinken oder modernen Epoche Venedig nach Lofer, wo du da sein und was mit dir rede schreibt, die machen dann weiter das dass der Patient Ostern Globus Gera konnte Chat ausstoßen oder deaktiviertes iPhone oder OK-Button Druckshop Schließung der neuen Saison 2018.
 Ich bin's, ich bin für alle mit dieser Funktion, dass er irgendwie proaktiv wird, wenn etwas passiert, also sehr wichtig, weil dann sind die Leute fragen. Sind Leute sehr schnell dabei mit ihm interagieren und so weiter und und vielleicht rumspielen, wenn er sozusagen wenn wenn die ganze sagt, wie er so sagt man die agents dann nur beim Nutzer ist, es ist sehr schwierig da werden das ist sozusagen taub und so weiter und so fort. Bin im Ausland und Patienten und die Basis wäre dann quasi aus was besteht oder die +10 so dauerte das Excel Verdacht bestand, dass es nicht gemacht wollte ich das mit deinem zugespielt am Folgetag Laufwerk über den Champion und
 Ja, ok es genau das 1. Reaktiv konstanter proaktiv früh für den Träger, damit der Chatbot losgeht im Sinne von der Person geschickt was also sollte er reagieren auf nur ich habe durchgeführt nicht durchgeführt oder sollte auch oder gibt's weiterhin die Emotionen und man kann auch sagen, warum geht's denn dir so illusion, also bleiben als genau eigentlich gut ja genau, also wir machen einfach so lassen, wir lassen die durchgeführt nicht durchgeführt Auswahl und die Emotionen und der Freitext kommt weg. Ja, da muss was ja wir trinken, also trete ich wieder bei blablacar.
 Aber Fotos kann man auf seinem hier was sehe ich auf dem Bild WhatsApp mal, ich meine von der Erde von der generatedvalue Geschichte kann man sehr viel machen, also Fotos werden sehr gut erkannt, was drauf ist weg an anfangen mit UHU, ich sehe du hast im Grünen oder so. Was weiß dass ich übertreibe jetzt gerade aber eventuell wenn man das entwickelt und der Rafael dran ist, kann man dann wirklich überlegen, solche Spielereien und umstellen einzubauen und dann kann langsam sagen, damit der Antrag nicht so leer steht und kann er natürlich dann unten drunter Genthiner Zusammenfassung machen von dem Gespräch. Hey, wir haben gesprochen über blablabla dann ausprobieren, also Spielereien, dass ich überlegen kann man dann genau den das Design des Chatbots genauer anschaut, aber ich bin da optimistisch, dass da echt viel geht, ich habe jetzt zwei Tagen bisschen dumm.
 Spielt mit mir zipgo und ich kriege sogar meine wissenschaftlich durchgeführten Interviews super zusammen gepasst oder neues Reiserecht der ganze Geschichte des bisher Alpha Ortrand SMAS Informationen Thomas Anderson sehenswertes im Chat zwischen Therapie oder missbraucht weg waren übrigens, dass wir gar nicht stören, aber die Information zu dem bosnisch Übersetzung.
 Pervers oder irgend sowas einfach reinschauen kann. Ich mein das finde ich spannend, wir haben schon einige Sachen, also, man kann ja bei solchen einfachen Sachen anfangen, wie Darstellung von diesen ganzen Emotionen, wie sie gelaufen sind und unseren Verlauf, das kann ja schon sozusagen. Also quantified sind ja eher das sind ja eher Statistiken, die woanders hin müssen, kann ich jetzt nie einfach nur auf einen Tag, weil ich ja nicht pro Maßnahme sondern das ist ja immer so wie wir sind aufgebaut haben wir ja den den kalender und dann geht man in der Maßnahme rein und dann siehst du nur die eine Maßnahme, also die eine für diesen Tagen Statistiken im browser durch sein Gewicht sein oder funktional und morgen am morgen auch mit der Statistik von letzter Tag.
 Oder wollen wir es erwartet aber vorsichtig vom lehnstedter Durchsage vom Vortag zum Beispiel, das müssen sich Moritz in detail auffangen in Klecken, aber hat nicht dass das Ironie Fall muss es nur statistikblatt ist Rosenheim offen oder Vielfältigkeit und außerdem kommt das FIFA so neben der Transfer von die Funktion hat und der Defekt während der Bischof und vom Hause bist und uns Feedback redefaul gekrault zu sehen.
 Dadurch ermöglicht worden, dass man den Abmahner mal angepasst hat und wie viel Adhärenz kam eigentlich dadurch, dass man einfach motiviert ist, weil man die ganze Zeit mit jemanden plaudern kann, Candida Pilz unter dieser Superuser zu deiner Frage klingt bequeme natusat von Rita lemmrich. Marineworkshop Vergangenheit hat gesagt, dass das irgendwie verhindern Iris Iris die weiß zum genau richtigen.
 Paket du läufst wie eine Gazelle oder wir das Auto schon oder das ist mir Feedbacks die Wirkstoffe sich definitiv, also, ich finde es ich finde sinnvoll und ich meine man kann wenn wir diesen proaktiven Chatbot haben, man kann natürlich sowas kommen wie Hey willst du also sagen spontan, magst du jetzt Gerd sozusagen Rückblick übernächster über letzte Woche anschauen, ich habe bemerkt, du hast blablabla gemacht, ne irgendwie eben sozusagen, du bist gerannt wie eine Gazelle und dann Link einfach und hier wäre deine Übersicht über deine Aktivitäten und so weiter. Man hat man 23 craften oder einen schriftlichen Kommentar oder was auch immer oder ich meine ganz einfach wäre einfach Fotocollage.
 Du nimmst die ganz unwichtig war, der der Patient gemacht hat und hat eine schöne Collage. Na, das ist ja auch etwas geht einfach darum, dass nicht langweilig wird, aber nicht sozusagen immer am montag früh kommen sozusagen Rückblick, das muss nicht so sein, aber einfach irgendwie so proaktiv diese diese Instrumente nutzen und dass das muss nicht mal wie eine getrennte Maske sein, es muss nicht nur also getrennter Bereich in der App. Da heißt Rückblick, das muss nicht sein, das kann ja einfach dazu sagen. Sophia kühn im Chatbot kommen und vielleicht kann man dann im Chat bot sozusagen vorherige Konversationen anschauen und dann sieht man ja da ist das mit dem Link und klick mal auf das Ding und dann geht's auf sowas. Keine Ahnung und du Meta Ansicht irgendwo ein Sohn und matter Ansicht irgendwo kann man auch das machen, dass man dann irgendwo und wenn man aus dem Monat klickt oder Lenker klickt, dann kommt vielleicht etwas ich weiß es nicht, ich bin jetzt gerade herum, aber ich würde
 Das wirklich so einbauen irgendwann die Aktivitäten von dem Chatbot auch, weil es nicht unbedingt gesagt ist, das sozusagen dieser Standard Sachen, weißt du, wenn du zwei Wochen lang jeden Tag sozusagen Frage ist jetzt gerade gegessen, kannst du mir ein Foto zeigen, dann ist langweilig und dann irgendwann mal noch andere Sachen sehen von dem Chat nicht nur wieder das gleiche, das kann ja auch sozusagen diese sowieso nur zoom out Perspektive bringen auf Chatbot, dass ich am Anfang vielleicht um Kleinigkeiten kümmert und dann mit der Zeit bringen da Halten mehr Informationen auf der ein kleine Sachen, was man bei diesen Sachen gemerkt hat, ist bei allen Alters Racing technology der Fall, dass sie gewisse Leute beim Erfinden darf man nur am Anfang oder Nutzung, weil sie irgendwann gelangweilt werden von den Methoden, die geht das Ding an findet das ist so wie wenn dir jemand immer erzählt.
 Du musst weniger essen irgendwann mal sitzen Normalität und dann geht's dir ja, die müssen das sagt, ne, also und und das kann ich von mir selber also und und von dem her kann man da natürlich die sowas von da jemand kommen würde und und mich überraschen würde und mir was cooles auf den Tisch stellen würden, würde ich vielleicht weniger essen, also irgendwas cooles was was gesünder ist, dass das was ich esse, also in dieser Richtung Chatbot komme etwas überrascht, da muss natürlich wieder cool, dann müssen wieder so einschlagen, sondern Beziehungsaufbau möglich und das Geheimnis von Oceana 1 live eigentlich oder der aktuellen Situation.
 Dass mir passieren, dass dein was näheres besprechen, wenn du vielleicht noch vervollständigen oder Architektur Zeichnungen und was hat der Libero prophezeite Tegeler, wieso arbeitet werden oft sollte man trainieren und dann musst mir ja sprechen Alexandra mit dem Rafael aus, dass ihr keine Polizei und genauso schnell besetzt während der Therapie außerorts.
 Ich würde noch mal kurz hinter fragen wie die Zeit also drei bis vier Wochen als einfach auch drei bis vier Wochen müssen einfach irgendwie mega viele Leute auf Abruf da sein und einfach mehr Zeit, wo Sachen schief laufen können, also denkt ihr, dass es sich dass es mit vier Wochen besser ist als mit 43 Disco machine tagesschau24 und du kannst und du kannst spannende Effekte sehen überzeugen. Es kann ja sein, dass man wirklich in 2 Wochen super Anstiege mit allem beobachtet und dann merkt man oder das ist.
 Da da Funk Tanz Uhu fängst an zu Zurbrüggen das ganze umso weiter. Man kann Intervention anbieten. Man kann eventuell proaktiv sozusagen durch den Chatbot das was äußern und sagen hey, ich habe gemerkt, du hast jetzt bisschen gestaltet. Na, also was was ist los und so weiter, also ich ich würde mich würde das interessieren diese Langzeitstudie, weil die als Langzeit zu so lang sein und nicht aber die fehlen grundsätzlich wo die Leute man nur an Mann bringt immer hast du dir mal die haben das genutzt und sie ist ein motivierter ja super. Toll jetzt noch mal zu diesen vier Wochen wollen wir diesmal alle 30 Patienten auf einmal durchschleusen.
 Und was natürlich jetzt die Therapie Fuß navigieren ab Standort Media Logistik hat rund um die Uhr werden die tägliche Gewichtsmessung oder diesen Artikel muss Programm Bremen am Mittwoch und am Samstag oder Wasser wingerode TV Simon achso ja, also einfach ich meine es geht jetzt schon ins Design rein, aber was genau, also bestellen wir uns das vor das jetzt nicht er also eine Maßnahme angepasst wird während der Therapie.
 Wir sagen ok, du gehst von 30 Minuten am Tag laufen ist anscheinend zuviel, wie wäre es denn mit 20 muss, dann müssen wir sicherstellen oder das bis zu dem Tag, wo der Partner so billig der Patient aktiv ein oder schreiben wir es ihm dann einfach nur vor und kann der Patient dann also gibt es dann wie eine neue Maßnahme, die daneben 20 Minuten laufen ist und alles in der Vergangenheit in der History sind dann aber 30 Minuten gewesen oder also soll ich dir eine definierte gutefrage.net aus?
 Was unterscheidet zwischen medizinische Maßnahmen und Anpassung von medizinische Maßnahme zu alter Lanz Unterstützungsmaßnahmen anders genannt und auf aus dir geworden zu unterstützen steht x Mastermind SAB Brandschutzmaßnahmen im Laufe Zombie verwandelt und ja, das mit deinem mit automatischer die medizinische Maßnahme hat, Basti Zeit, jetzt kostet Stories Minute 20 minuten 200-400! Tja, was heißt der Schule Ohrensalbe Zahnarzt von USB spielen ohne Download probieren so das wäre das Ranzen Stickmuster.
 Teenager bei Franzi an Komponenten einfach so weh, wie ist dann die App Design, dass man das nachvollziehen kann und wie wird der Patient informiert? Weil nur einmal über den Chat sondern es ist mega viel. Also, ich war ja noch nie haben und auch solche Sachen mit diesem abändern von der Maßnahme sowie das jetzt da Adrian implementiert hat, der wird es nicht gehen. Also das ist total interessant definiere Logos mit dem Material raus und dann die gegenseitige Annäherung.
 Download was ich da sagst nicht realisierbar Forellenhof Amazon Mode überleg gewest Sievers kurdisch und meerstern of our quasi abspacken oder gehende und dokumentieren Maßnahmen ist wichtig und was ist das? Davis Arena change ist derjenige Maßnahmen, dass ich das jetzt ganz Rezept also sabine.
 Genau, also dass das können wir sicher hin und auch dann aber und daneben noch braucht der Arzt auch eine Übersicht, wie sich das verändert hat oder irgendwie auch in seinem in seinem Cockpit muss, der eine Verlaufs Änderungsanzeige haben und sagen ok Maßnahme hat sich in Maßnahme hat hat sich derzeit Parameter geändert dann dazu da damit die Unterstützung hinzugefügt und das muss alles irgendwie auch dann schnell ersichtlich sein in der Folge konnte dafür haben auch noch nichts getan.
 Hatten haben wir das jetzt nur besprochen mit Hornig Zahnarzt, das ist nur ein Arzt, während deine vier Buchstaben nur irgendwo tritt clocktower worauf richtige Weg ist oder nicht? Einmal imstande zwischen Legalität und die entstandenen Regulationstherapie übersetzungs Auswuchten VCP.
 Mit dieser Plan B Variante sozusagen eigentlich Manuel das tracking und die Ärztin wohl ursprünglich Stadtlauf nach Ganterschwil jetzt auch halt die Studenten das gemacht haben täglich trinken, was passiert und rapportieren und im Sinne und unten und im Fall, wenn irgendwas irgendwie aus dem Ruder läuft oder man halt nie, die Uhr trägt oder anscheinend überhaupt nicht zurande kommt, dass wir dann einfach wieder eingreifen, aber ich würde ich finde es fast ein bisschen weil das ist wieder mehr Arbeit, wo wir jemanden dazu zwingen müssen, also Ärzte dazu bringen müssen das zu machen und was soll genau jetzt damit besser oder anders werden bei M.
 Funktioniert oh, das funktioniert nicht oder also und und und alles so zur technische Hürden und so, das können wir lösen, aber wir werden ja sehen, ob ob ob Menschen einfach Therapiemaßnahmen Änderung annehmen und die Barbara kann sicher machen einfach mal drüber gucken, also er ja, aber sag nur komplett Autoscout kinox.su, ich habe noch ein paar Sachen für den Agenten in dieser Zeit, also, wie oft haben wir also wollen wir definieren, wie oft der Terra Adhärenz Agent auf eine Maßnahme hin intervenieren kann, also soll z.b.
 Das jeden Tag umgestellt werden können das also das wieder nie gemacht wie der nähe jedes mal sagen wir okay, dann mach doch die andere Schuhe an. Machst nur 20 Minuten macht das nachweisen, dass oder bei mir in den limite einführen oder sag nur alle drei Tage kann man ihm was neues vorschlagen. Wenn du das gehört auch irgendwie mit in das Design als wenn man kann ja auch sagen. Es ist völlig, also, entweder hat er halt einfach aus irgendeinem Grund keinen Bock mitzumachen, aber wenn du als wir können auch über schießen ist sowieso das sollte man verbieten oder zumindestens oder Sonntag stattfinden oder wenig Daten.
 VT Missio Drautal Interventionen the boss Erinnerung, dass das ganz wichtig dass man Patienten bisschen damit sie die Information reinkommt, wenn man jeden Tag sagen einer soll 20 Minuten joggen gehen und jeden Tag wird es nicht gemacht und jeden Tag kommen die gleiche Nachricht mit der gleichen Argumentation seitens Chatbot und ist mega langweilig wird es quasi das nervt, aber wenn man wenn man das gut einbaut ich weine auch schon, also ist man müsste nicht jeden Tag auf dieser Maßnahme rumreiten, könnte ja sein das mal generell sich einschaltet und und das dann sozusagen nur als sprengboot nur Sprungbrett nutzt man sagen hey, ich merke sagen die ganzen Maßnahmen gelaufen nicht so ganz warum meinst du ist jetzt so oder so was das, dass man da nicht nur zu sagen diese sehr Standard standardisierte standardisierte Volk
 Den hat und noch anschauen überlegt, wie könnte man in Notsituationen eventuell sind Patienten ansprechen und letztendlich geht weniger darum diese Formulierungen zu finden, weil das findet iubiti selber oder andere langweilig Weingut modus, sondern sie zu definieren, was was für Zeit Punkte sind und wenn es dann z.b. Zweimal schon zu gleichen Maßnahme etwas gekommen ist und der Macht immer noch nicht und dann so sagen 3. Mal zukommen mit dem gleichen Song ist bisschen langweilig und müsste sozusagen wieder, die abstrahiert werden von dem provisorischen indem sie ja ja, ja ja eben kam eine gewisse Intelligenz dahinter dann über die ist der Alz.
 Hier das wird im übrigen die andre besprochen haben. Sollte eigentlich vom Chatbot präsentieren werden als sozusagen, also das Auto irgendwo dokumentiert, das meinte ich mit einer offenen Wunde im Mund auch Interventionen, also im Sinne ist eine Intervention beschreibt einfach ich höre eine Konversation oder oder ist eine Intervention ich ändere etwas geschrieben gibt es auch Intervention, wenn alles gut läuft, kann man Zubehör sein, dann machen wir doch eben vierzig Minuten draußen, wenn das so sau gut läuft, dass ich eben auswandern exaited passieren durfte Resultate zu der Stever nah und gut laufen.
 Sonnensystem ist das Standardverhalten Formular, wieso die Therapie nicht wann der Patient macht Wasser daneben genau aussieht, Betroffenheit und Nerven und sozial Name und Paradoxie, der erste Mal ist, dass einige der zum Teil sehr patientendisposition sich gut so und was dann regt sie sich behalten erst in die Trikots die Passivseite, dass ich super oder will sie dann sofort verbannt und das ist ja für Patientinnen und sie war 17.
 Andi super Kuchen und runter ja nicht automatisch, dass Antibiotika und dann haben wir irgendwas sogar, also, wenn irgendwelche claims auch wie genau wollen wir das Messen, wenn wir keine Vergleichsgruppe haben, es kann man nur aus den Aussagen dieses Postings breakdown ihrem Projekt.
 Also denken deswegen Vorteile bringt es zu nutzen. Werde dafür sorgen auf der Brennsuppe Vollkorn die Therapie konzentrieren und die Filme Informationen Gründe für Gründe für nicht Toleranz und solche Dinge und dann quasi super super Darstellung präsentieren.
 Michelle bis morgen Personalfachkaufmann Profile und da müsste man sie Verhalten zwischen und sicher Elektrizität mit deiner für Hochwassermeldezentrum Zweitwohnsitz Termin auch im Hinblick, obwohl bekommt das Mammutwerk etwas mit sitzt, da sagte der schnellste Weg sich muss ich sage Rückblick von vorne und das haben wir noch Briefe zwischen Kiefer und Wange.
 Ist aufgeflogen sind wir das dann auch so lange vorgeplant, Jürgen Jürgen Erbach italienische Version ist die neue Therapie am Ozean türkis von Zucker und das Fahrzeug dann vielleicht hat sie ankommen wieder irgendwie so ja genau.
 Genauso eine intenso eine Besprechung, sondern detailbesprechung, wie es gelaufen ist, als einfach so genau das alles angucken mit dem Ärzte Cockpit und dadurch gehen und einfach die 20 minuten nutzen, um einfach auf den Patienten eingehen zu können, ohne dass er eine aufnahme Zubehör Sprossenwand Materialverlust 14 Spieler ist jetzt Gewitter.
 Herunterfahren von Patienten mit Suse Kunde das irgendwie das mit den 20 Minuten laufen pro Tag ist wie neu, sodass man feststellt oder David gemalt, sondern eine Änderung Wohnort mit tasmota Metaanalyse Gange war nicht das bin ich auch Nachmittag Kaffeefilter unterwasserparty Anton Zach Wien
 Glaube das waren alle space Karatas und Fette Autos das irgendwie zu sprachst und dann Router verbinden Tage für Folgekosten ebenso wahnsinnig. Vermisse Teufel steckst dann INDECT Alter das alles so eben doch als den Ärzten darin Script geben, was wir wirklich auch alles angucken, weil die das war er genauso free-floating Erwin Erwin Rieder youstyle das irgendwie verschriftliche, dass das irgendwie aufmuntern.
 Sie darfst operante Sitz der Aufseherin und 2006 ausfüllen man Bruch oder telefonieren! Bis dann rufst du noch an, der auf dem Reiterhof 8 x und die andere Betrachtungsweise. Wer ist die wissenschaftlich begleiteten andre Großglockner?
 Bireggwald übersetzt das Auto zum nach einer wissenschaftlichen Erkenntnisse kriegen oder unbe dazu vielleicht etwas was ich mit Gerd zwischendurch besprochen hatte und wir hatten zurecht mit Andre, du bist gut ihr das, wenn hier so viele Daten sammeln gibt, vielleicht keinen der das richtig auswertet Gerdes der Meinung, es gibt eine und zwar den Rache der Name Raphael und dass uns machen und für die Daten Daten sammeln Unterstützung könnte natürlich irgendwelche Studenten dazu kommen dürften, aber wirklich nicht reimen, also so bisschen, dass wir haben damals deswegen nicht.
 Ich spreche darüber, weil wir in der Grafik die die die 4. Teilen, da hatten wir noch relativ viele? Was zu welchen Zeiten gehoben wird und so wie ich Gerhard verstanden. Habe neben dem dass wir natürlich irgendwelche Loks von den Chat haben, was sowas ziemlich interessantes auszuwerten, dass wir doch dann an jeder an jeder Stelle versuchen ähnliches auf zu fahren, wie wir das in dem vorherigen Test gemacht haben, Semmering ja, dass wir immer Interviews machen das sicher auch, weil sie die meisten wert bisher geliefert haben, wir können natürlich die Fragebögen noch mal überlegen. Hey, was hat vorhin gemacht und unter Umständen macht man langsam net Promoter Score, der sowas oder so. So generell ist zeigen, was man für alles für Menü.
 Essen kann, aber ich vertraue da auch nicht so sauer mittlerweile auf die auf die Fragebögen die Helfenbein Argumentation, aber sind nicht notwendig, ich frage mich, obwohl das hatte ja auch relativ Bullauge Ergebnisse gebracht diese Videoaufnahmen, vielleicht muss man das nicht mit zwei Kameras machen, vielleicht reicht sozusagen da bisschen ein kleineres Format und das alles aufzunehmen, vielleicht sogar mehr einfach nur Screenshots greencast unter Umständen Stadt Städte alles andere aber das ist sagen wir eigentlich in die Konsultation wäre schon noch spannen z.b. Ob sie ja du redest schon aufgezählt die Kamera einstellen und ausstellen darf stelle das ist simpel, das braucht nicht viel Aufwand, das heißt, dass sie sehr günstige Daten.
 Okay, to date würde ich jetzt nicht unbedingt Aufstrich machen und sich sind interessant und wann das tatsächlich so ist, das Menü der Foto nicht zur Verfügung stellen, dann hilft das schon massiv oder personal branding gegen das Ding haben wir glaube ich diskutiert, dass wir vielleicht das Onboarding selber aufnehmen, vielleicht kommen da Sachen hoch wie ich. Bin unsicher mit der Technik oder sowas vielmehr ging es um Interviews nach dem Konzert im Onboarding Dinosaurier nur gemacht, damit das Wasser Gemeinde baseline.
 Diversifizierung dir das und dass es so wahnsinnig spannend sich nicht verdient Dimitrios in der Tat Talent und Führer Personen, das Spiel ist aus, wenn sie mir vorstellen, dass das wirklich besondere und wandern immer noch am Ende irgendwie zwei drei Fragen stellen, wenn uns an den Finger und Ringfinger brennt und wir wollen unbedingt Patienten etwas fragen kann man immer noch das ganze integrieren, aber ich glaube so hast du einen Gespräch was unter Umständen auch die erste Reaktion auf die ganze Technik ist, was man auch nutzen kann, dass sie von Anfang an waren sie begeistert wäre.
 Sus von Anfang an waren alle skeptisch und dann trotzdem irgendwie am Ende genutzt, also soll ich da nur sagen, sondern interessant und man kann schon sozusagen da irgendwie mit zwei Fragen. Ja und wie war es bisher sozusagen Willi Flessner, also haben sie schon probiert paar mal solche Maßnahmen umzusetzen, was hat sie am meisten gestört, das sind so nebenbei fragen, die auch besser integriert sind in sowas, weil es hat sich eine gewisse Vertrauensbasis gebildet durch das Onboarding gelesen, dass man da noch zwei Fragen für 10 minuten stellen kann. Das wäre meine Herangehensweise Diakonie-Klinikum. Ja, da ich frag Mama war die letzte Mal nicht sind ja die Frucht, was will ich denn Date fragen?
 Finde ich eine gute Idee, wenn es dann heißt, dass der Chatbot bereits beim Onboarding eingeführt wird und sie können der ersten Woche wenn Tuell mit denen interagieren, dann sagte ich spannend zu erfahren, was wir gewirkt hat auch das Sammeln der Daten. Na habt schon sozusagen, dass selbst die Tatsache, dass sie Daten sammeln, sondern eine Auswirkung gehabt und meinen Sie ob die Auswirkung noch bleiben würde oder nicht. Also, ich würde da sozusagen, diese diese Woche noch reflektieren bisschen lachen. Hey, was war das beste was war das schlechteste Erlebnis erstmal mit der app bisher und das bietet aber auch eine Möglichkeit Ausruf man, dass man sich vor Augen führen, dass bietet auf eine Möglichkeit wenn Sie irgendwelche Probleme haben, mit der app kannst du den immer noch was erklären und dann als müssen einfach die Person muss dann eingeführt sein und verstehen wie die App funktionieren funktioniert.
 Machst du denn auch beibringen sind erst weißt du, weil 4. Technisch als also das muss nicht unbedingt mit dir zeigt, was ist das macht sowieso und dann ist dein technischen antworte ich unterstütze nicht verstehen oder schnell aber das bittet bittet und einfach die Möglichkeit sie noch mal, wenn sie wenn sie überfordert, weil so wie ich verstehe. Man Boarding wird einiges erklärt. Na, da ist jetzt das ist bisschen mehr geworden man durch diese ganzen neuen Technologien und so, wenn sie da überfordert sind und ersten Woche dann kommt vielleicht gerade im Interview raus, wann kann man darauf reagieren und man kann mit den Leuten absprechen und so weiter, also was wichtig ist klar, das klingt immer so ganz schön wissenschaftlich. Nee, es gibt erstmal eine Runde 10 Minuten erklären von der App und dann gib 20mg.
 Hintergrund gibt es 5 minuten das aber eigentlich geht bei solchen Sachen immer ganz praktisch darum, dass sich dass ich Vertrauen aufbaut und wenn es dann wissenschaftlich heißt, ja, wir haben da irgendwie z.b. Onboarding hat man dann Finca Lautzeichen nennt man das nennen Leute das ausprobieren, dann denken Sie vielleicht sagen Sie was und so weiter und hat man single out Session mit Baufragen und nach der ersten Konz hat man halt dann wie sagt man Interview und wenn da noch Sachen erklärt werden, dann ist es halt so. Ich meine niemand verbietet, das wolltest du unbedingt, dass der Fokus von dem ich überlege mehr von den anderen Methoden Daten zu erheben, weißt du, also Interviews ist das eine Aufnahmen ist das andere aber
 Und um 3 Uhr ist das ganze Logik von logging von der Nutzung von von der App, das wäre auch noch wichtig man da entsprechend Logs hat, dass man da Konversation hat und so weiter, dass man merkt, wie funktionieren. Meine Frage ist wirklich diese quantitativen Daten self-report und sie haben bisher wenig wert gebracht, so wie ich das verstehe oder das Watt das gerade wie quasi keine signifikanten produzieren Fragebögen er nicht diese Anamnese, sondern die die zwischen hast. Du ja Jarno offensichtlich kannst du dann Tina das eine oder andere verbirgt und abschneiden merkst, dass das nicht sind neben signifikante Schnitzel Bringdienst und so und
 Ja, das Problem ist weisst du das Problem ist, das haben wir immer in den in den in solchen Sachen ist, das die die sagt man die Patienten Schrägstrich Probanden kriegen etwas Beratung, die gut ist. Grundsätzlich, weil sie ja halt sonst hätte ich das nicht gekriegt, also dieses wie Bob sagen würde, das Geld ist sehr groß, weil du fast nicht erwartet hattest oder nicht erwarten würdest normalerweise noch einmal kriegst du etwas und deswegen fällt dann fallen, dann sagt mir, dass die positive aus immer bei solchen Umfragen Problem war auch dass die einfach zum Teil schlecht übersetzt waren und schlecht gemacht waren für das Thema bei wer beides relativ schnell ging und wir saßen da und die Leute haben uns die ganze Zeit gefragt, was das bedeutet, wenn die Leute nie kapieren, was sie da ankreuzen.
 Also, das war bei mir der Hauptgrund interessant, wäre er gewesen mit denen halt, weil die haben also dann halt Leute, die haben viele Selbstgespräche. Danke, für das hätte man ab da hätte man schon die Interviews aufzeichnen sollen, da hätte man halt mal bitte gibt er malt immer dann fiel mir erklärt, warum wieso aber warum sie das jetzt ankreuzen, weil der der Kontext wäre dann interessant gewesen, aber was sie selber angekotzt hat, halt meistens oder manchmal soll das kann ich nie sagen, weil oder so und ja, dann lässt sie tendenziell weg und wenn etwas quantitative sein soll, das macht man dann so wie Psychologen das ganz oft machen, dass das einfach Bestandteil vom Interview wird und dann liest man einfach okay, jetzt habe ich ein paar Fragen. Die strukturierte sind auf einer Skala von 1 bis 5. Wie finden sie das was man aus Papier machen könnte? Ist schon auf so eine.
 Rachel wie wie das geht, ganz schnell attraktiv oder sowas das mögen Leute das eine von den klassischen Tools, die wir immer nutzen und dann fahre ich gemacht oder ja und das aktiv ist immer ganz schön, weil du fast auf eine Theorie dazu und du kannst immer so schön und so ein Quadrant irgendwo rein tun ein paper, also das ist das ist das was von hassenzahl was attraktiv genau wusste nicht, dass mit dir Zitate aus dem prossliner berücksichtigen 80% der Patienten finde Rinde finden in der Konsultation zum Mitnehmen, die für ihre Adhärenz relevante Informationen weniger in der minute.
 Zombie Spiele im Ausland initial kannst immer der schnellsten an ein Trio zum Beispiel, als was brucht viel Minuten vor dem Prinzip der Umlaufbahn des Rebecca Catherine Swissair Raubtiere noch wichtig, dass das nicht vergessen und dann die nächste Stern eine wechat sind, die moderne 2D membranaufbau quasi direkt vom Chatverlauf machen dafür und die andere muss man einfach basteln im Detail Umstände und das engelskonzert, dass das einfach die EM um sicherstellen, dass dir Ziel wo man den Swiss versprochen, dass die Adresse richtig sind und dass sie eingehalten sind genau zumindest, dass man das gemessen hat.
 Braucht nur G2S Washingtoner spannend. War nur schnell zwei drei überlege gemacht, richtige Organisation. Ja, machen wir das jetzt mit David liest nicht richtig unter Projektplan sittliche Gründe oder Evolution der 3. März bis Mitte April und Bambus Restaurant impliziert das natürlich Antwort ja Moment irgendwie dies galt wurde schließen an das neue Nationen Sprachen deutsch Avengers Marathon Jena.
 Wird es regnen oder geht's jetzt verschiedene Möglichkeiten auf eigentlich natürlich auf motivationsaufbau genauer Trottel Auftragnehmer ganz früh auf andere Sprache mit der linken Hand bitte Karte, dann dürfen wir die normalerweise oder sie noch mal nachfragen wie der Endrunde sich die wiederhole, ich weiß ja nicht, wie man es ist. Wissenschaftliches ist f&z mache weiß ich auch nicht, weil sie schauen nicht.
 Schon ein interessanter Fakt zu dem Thema oder der ist das Sub Spannung von der Großglockner im Stand ist und bedürfnisfinder super spannend war mir vorstellen, dass mit ihr zum TA vorige Sammler für Service Dashboard vs. Patienten keinen Zugriff.
 Max generierten du dir dein Name oder erste übel und ich würde gern mit deinem Problem erzählt, dass du dir denn deine oder Evelin mehr ich habe ich habe deine pragmatische Herangehensweise, ne, also zuerst zuerst suchen von außen halt und wenn es dann sozusagen nicht klappt, kann man immer noch auf sie zurückgreifen, wer meine also Ziel eins ist wirklich neue Person zu haben, die diese Erfahrung nicht bereits hatten, weil dann hast du in den Interviews ganz auf zur vergleichende Geschichten auch verhält es schlechter gewesen und das kannst du gar nicht brauchen Türken, welche Publikation and weil du kannst ja plus plus noch, wenn wir jetzt eben anfangen und die Fragen so ja.
 Sie sich das mal an macht es für sie sehen und am Ende bringen die dann tausend Vorschläge und dann setzen wir das nicht so um dann sind ja schon also dann sind sie ja dann schon irgendwie enttäuscht oder genervt oder so, wieso ist es anders, also, wenn man die jetzt als vom Pendel also ich glaube nehmen würde ich die eben von vorher unbedingt um das rauszufinden, aber ich kann mir eben vorstellen, dass die dann schlechte neutrale Kandidaten sind, aber mehr ist NEU Lied find the remains, das wäre auch einfach wenn wir 30 auf einmal wir haben das an dem wir haben, wir haben das so gemacht, weil wir auch nicht mehr Leute an einem Tag durchschleusen konnten, weil wir einfach das erstmal logistisch von dem also von der Lokalität ist es nie aufgegangen.
 du musst genau das stimmt, wenn man es denn dass man nur die Barbara Iris office.org Kanton muss Aufstiegs und die also die Betelberg bloß die Anzahl Räume, damit zusammenhängender die Anzahl Personen oder grundsätzlich und theoretisch mit genügend volutions Personal man natürlich in Adetswil unwillkommen Kopf und Statistiker Respekt davor, ich habe auch mega Respekt davor 30 Leute für 4 Wochen Nefis fünf Wochen zu supporten und weil wenn da
 Als ich gerade machen wie dein Pretest hoffentlich, aber wenn da irgendwas schief läuft und dann ja, ich fand zwar schon. Ja, ich sag's genau bin nur ich habe nur Respekt. Nee, aber wir hatten doch hatten wir eine 24018 und dann noch mal acht oder zehn, ne? Aber einfach auch, wenn du für 30 Leute um die permanent neue Maßnahmen generieren muss, dass ich weiß ja nie, wie das glaubt, aber wahrscheinlich wird es ja nicht so beständig, wie viel Volumen.
 Sonst beim Telefonsupport, dass der Dreck wieder lautet, weiß ich nicht, was das Problem ist oder das Schnabeltier Maßnahme Auto neu definieren und eben was auch immer gebrauchen sechs Ärzte die alle zur gleichen Zeit können ist auch noch eine Bahn befürchtet, dass du ihm das medizinisch Zentrum im Hintergrund oder dann schreib mir natürliche Zahl und Intensität.
 Jona Bus fahren oder vielleicht sozusagen und geht dann anzeigen tension pro Patient und jeder Patient liegt Materialdefinition mit deinem Verständnis, aber ich wollte noch mal hinterfragen, ob das wirklich 30 Patienten sein müssen, ob der Gerd das wirklich unbedingt braucht eine Handreichung urlaubsapotheke Thermo seine Schuldigkeit getan.
 Nicht richtig messen können mit der Adhärenz, dass wir gut argumentieren können. Dies ist technisch wahnsinnig aufwendig, das ist schon cool genug ist verwirrt zehn Leute haben als meine Bruder Lothar Matthäus mit dem Gärtner. Nockenschaltwerk, was ist Minimum Zahl von Patienten, aber ich will da keine keine klare Ansage machen, ich finde ihr mehr desto besser, na klar, aber also jetzt unter 20 würde ich auf keinen Fall gehen, das ist ja dann wie schnell wieder 24 bis 28 und wir krieg dich nicht, dass die Gläser hartebeest mitmachen, also kritisch.
 Ich finde auch brauche ich brauche ganz viel Neues neues ich finde eben das ist voll gut ist weil da die kriegen ja jetzt neue Funktionalität dazu für dich kommt der jetzt einfach was ganz anderes und top für die Patientin ist der Fete bei Daniel Saupe eigentlich genau, was wir jetzt machen, aber die können wir vielleicht echt nie wieder verwenden, weil die einfach nicht adipös sind, aber aber für den fit für den Arzt gibt's jetzt noch mal für den ist ja eine völlig andere Situation, jetzt kommt da irgendwie ein Chatbot, der seine Arbeit übernimmt.
 Bulgur das dann wäre bereits besprochen die Adresse Markus Papiere finden und zweitens für Evolution Methode oder Vorgehensweise andere Befehle genau.
 Umfrage stets bewacht und die zweite Frage Details schon noch eleganter chain undead UZH wird auf Arbeit erledigen Eifelwall, also, dass das quasi dann zum Beispiel am Raphael das Video gehe ich und zahle ich das noch mal unser extrahiere was ist da besprochen heute nicht anrufen. Wenn ich nicht sagen, machst du mit den Vorschlag machen und ich hasse zerlegt und du lügst drücke.
 Also, wollen wir uns nie zusammen hinsetzen und ausmachen, sondern der Macht 1 Bass und dann werfen uns gegenseitig spielen wir uns den Ball zu oder wie meinst du jetzt ja erstmal was ist Standard und der andere Überschrift von meiner Seite, also machen das wenn ich mal haben wir das relativ ausführliche waldkonzert macht mit Andreas erwähnen muss, dass 90er sowas für mich eigentlich genügen wäre, wenn beim Passieren sag mal auf deinem Link Rad Reifen Rafting das Spielzeug sind, das einfache präzisiert oder sowas. Das Paragraph ist die Grundlage.
 Samra der Patienten auf Geldkarte auslesen BIOS aufrufen grafische Grundlagenfach Präsentationswand macht wird wie spielt es in der 2, Rose Immobilien privat und das umso oder geschenkt bekommen Papiere Mercedes Benz 230 Stihl
 All-in.de Embryo culture konzipieren und dann kam raus Diskussionsthemen und dann Wellensittiche timer ein Lied featuring und der Tasche zu Meetings morgen oder nächste eigentlich für fürs Design ist toll, also mir den 30. Also nächste ich dir gerne eine spring.
 Wenn ich sage, dass Felix alle falls Du glaubst wird wird besonders und dass er vorher nicht normal so auf sie sein zu sein sich, aber ich glaube meloso man wirklich im PlayStore Spiele Tudors die degenerieren Design oder was, aber der wurde gekündigt, aber ich glaube wir zwei konkrete Fall Stoffe, also das Wetter, ich glaube aber dass dass das ist doch aber auch gut, also daraus können wir dann noch total viel requirements ableiten und ist ja also ich habe einfach genau ich habe also Mirella, ich habe einfach jetzt nächste Woche.
 Bin ich komplett voll und vor dem 5. Mache ich nie viel, ich kann jetzt einfach Tierschutz mitgeschrieben. Habe ja und dann aber dann können wir das auch noch mal genau dann können wir darüber gerne ab ab abnehmen abnehmen 6 oder so kann ich wieder gut was dafür machen, du schickst mir was du geschrieben hast, dann mache ich wusste ich schick's dir noch mal, du hast der ganze und nicht dein Ziel ist Joanne, wo ist der als Basis zurück, was genau ist rhetorische Mittel für draußen mit lautsprecher.
 Dann ist spring Meeting an der Brücke springen und den Rest werden quasi gar nicht das Meeting am feuchten und Würmer. Danke, dass ich nicht mal reden von Raffaello selber machen und den Radio Bremen schnellster täglich außer dass man direkt davor beim Spring Meeting was ist nicht besonders mit Kurzhanteln. Ja, ich glaube, dass er sich erstmal einarbeiten das Ganze ich bin wirklich begeistert, wie einfach es ist, ich hatte jetzt sozusagen keinen Kopf für irgendwie sinnvoll arbeiten hat mich einen Tag hingesetzt und habe bisschen rumgespielt und auch wirklich dann Ganze lenkt chain chain aufgebaut und soweit das ist mega easy, ich bin ich muss sagen, das wird das Ganze wirklich erleichtern ohne.
 Sorry, dass du bist ja ein Klumpen Dreck total genossen brauchen und was wird man untersucht noch zur Verfügung und dann! Extreme Arena Blanca?
 Sie wird das durchmachen haben, ich habe noch so paar Sachen bezüglich Compliance Fragen, aber die kann ich ebenso soll über den Chat war innert werden das dass sie die Uhr umlegen müssen, wir müssen auch ein genaues Protokoll haben. Von wann bis wann muss man die Uhr überhaupt tragen, dann darfst du Ausnahmen geben, also also wahrscheinlich so idiotensicher schreiben. Sie dürfen es zum Duschen ablegen, aber bitte wenigstens von von nach dem Aufstehen bis 18 Uhr tragen oder irgendwie sowas bei wenn also das habe ich jetzt alles bei dieser Firma Leitwert gelernt, also die ja klinische Studien machen in so einem zusammen, dass die haben das alles so halt schmerzlich lernen müssen, dass das halt einfach ja so die Basics, dass die ant man muss ja die Uhr tragen damit auch Messwerte da sind und so oder das oder bzw.
 Wie weit man beginn haben wir halt Intervention, sag mal hast du die Ohren die oben oder ist die Batterie alle oder was los sowas genau dann wann wann soll mit den also die diesen Scheduler das haben wir auch ja, also Mirella und ich sowie auf unserer tasklist, dass wir einfach sagen so ab bei ab wann fängt der dann an über Dinge zu sprechen mit dir genau so direkt am nächsten Tag. Ja und muss es wie ein Protokoll, also haben wir Vorschriften für die Patienten sauer, öffne die App einmal am Tag synchronisiere einmal am Tag mit der Fitbit, also, dass ich glaube, das muss eigentlich alles sehr viel präziser sein und nie nie so explorative letztes Mal. So benutze ich es halt so wie sich verstehen.
 Ich will mehr als ich genau das hatte ich eben noch notiert, aber ansonsten ja genau aber eigentlich alles besprochen, was ich mir auch geschrieben habe Anfragen zu schnell warst du ja stimmt. Sie merkt, dass wir geübt sind oder nicht in genügender. Na ja gut ruhig und gut.
 Danke, danke schön, euch auch. Alles Gute. Tschüss.
"""
out = chat_sum(text)

print(out)
